import {useEffect,useRef,useState} from 'react';
import {onIdTokenChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,sendEmailVerification,updateProfile,type User} from 'firebase/auth';
import {doc,onSnapshot} from 'firebase/firestore';
import {auth,db} from '../firebase';
import type {Lang} from '../i18n';
import {labels} from '../admin/i18n';
import {createOrder,syncUser,type Data} from './client';
import {OrderCard} from './OrderCard';
import './style.css';
export function Booking({lang,pickup,destination,serviceType='taxi',category='economy',paymentMethod='cash'}:{lang:Lang;pickup:Data|null;destination:Data|null;serviceType?:string;category?:string;paymentMethod?:string}){
 const t=labels(lang),[user,setUser]=useState<User|null>(auth.currentUser),[orderId,setOrderId]=useState<string|null>(null),[settings,setSettings]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[verified,setVerified]=useState(auth.currentUser?.emailVerified||false),[notice,setNotice]=useState(''),requestId=useRef<string|null>(null);
 useEffect(()=>onIdTokenChanged(auth,u=>{setUser(u);setVerified(u?.emailVerified||false)}),[]);
 useEffect(()=>onSnapshot(doc(db,'settings','platform'),d=>setSettings(d.exists()?d.data():null),()=>setError(t.dataError)),[]);
 useEffect(()=>{setOrderId(null);if(!user)return;return onSnapshot(doc(db,'activeCustomers',user.uid),d=>setOrderId(current=>d.data()?.orderId||current),()=>setError(t.dataError))},[user]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const f=new FormData(e.currentTarget);if(!user){let u;if(f.get('name')){const c=await createUserWithEmailAndPassword(auth,String(f.get('email')),String(f.get('password')));await updateProfile(c.user,{displayName:String(f.get('name')).trim()});u=c.user;await sendEmailVerification(u);}else u=(await signInWithEmailAndPassword(auth,String(f.get('email')),String(f.get('password')))).user;await syncUser(db,u);return}if(!pickup||(!destination&&serviceType!=='master'))throw Error('invalid-location');await syncUser(db,user);const result=await createOrder(db,user,{serviceType,category,pickup,destination,phone:f.get('phone'),notes:f.get('notes'),customerName:f.get('customerName')||user.displayName,paymentMethod},requestId.current||undefined);requestId.current=result.id;setOrderId(result.id);setOpen(false)}catch(e){setError(String((e as Error).message)==='active-order-exists'?t.orders:String((e as Error).message)==='service-paused'?t.pause:t.dataError)}finally{setBusy(false)}}
 if(orderId)return <OrderCard id={orderId} lang={lang} onClose={()=>{setOrderId(null);requestId.current=null}}/>;
 const enabled=settings?.ordersEnabled===true&&settings?.services?.[serviceType]===true;
 return <div className="spark-booking"><button className="order-button" disabled={!enabled||!pickup||(!destination&&serviceType!=='master')} onClick={()=>{setOpen(!open);setError('');requestId.current=null}}>{lang==='ru'?'Заказать':lang==='tg'?'Фармоиш додан':'Buyurtma berish'}</button>{!enabled&&<p className="spark-caption">{t.pause}</p>}{error&&!open&&<p role="alert" className="spark-error">{error}</p>}{open&&<section className="spark-card"><div className="spark-heading"><h3>{user?t.orders:t.enter}</h3><button type="button" onClick={()=>setOpen(false)} aria-label={t.close}>×</button></div><form onSubmit={submit}>{!user?<><label>{t.name} <small>({lang==='ru'?'для регистрации':lang==='tg'?'барои сабти ном':'ro‘yxatdan o‘tish uchun'})</small><input name="name" maxLength={80}/></label><label>Email<input type="email" name="email" required autoComplete="email"/></label><label>{t.password}<input type="password" name="password" minLength={8} required autoComplete="current-password"/></label><button disabled={busy}>{t.enter}</button></>:!verified?<><p>{lang==='ru'?'Подтвердите email перед первым заказом.':lang==='tg'?'Пеш аз фармоиш email-ро тасдиқ кунед.':'Birinchi buyurtmadan oldin emailni tasdiqlang.'}</p><button type="button" disabled={busy} onClick={async()=>{setBusy(true);try{await sendEmailVerification(user);setNotice('Email ✓')}catch{setError(t.dataError)}finally{setBusy(false)}}}>{lang==='ru'?'Отправить письмо':lang==='tg'?'Фиристодани мактуб':'Tasdiqlash xatini yuborish'}</button><button type="button" disabled={busy} onClick={async()=>{setBusy(true);try{await user.reload();await user.getIdToken(true);setVerified(user.emailVerified)}catch{setError(t.dataError)}finally{setBusy(false)}}}>{t.refresh}</button></>:<>{!user.displayName&&<label>{t.name}<input name="customerName" required maxLength={80}/></label>}<label>{t.phone}<input name="phone" type="tel" required pattern="\+992[0-9]{9}" placeholder="+992901234567" maxLength={13}/></label><label>{t.notes}<textarea name="notes" maxLength={1000}/></label><p>{t.cashText}</p><p className="spark-caption">{lang==='ru'?'Цену предложит водитель. Вы подтвердите её до начала поездки.':lang==='tg'?'Ронанда нархро пешниҳод мекунад. Шумо пеш аз сафар тасдиқ мекунед.':'Haydovchi narxni taklif qiladi. Safardan oldin siz tasdiqlaysiz.'}</p><button disabled={busy}>{busy?t.loading:lang==='ru'?'Отправить заказ':lang==='tg'?'Фиристодани фармоиш':'Buyurtmani yuborish'}</button></>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="spark-error">{error}</p>}</form></section>}</div>
}
