import {useEffect,useState} from 'react';
import {doc,onSnapshot} from 'firebase/firestore';
import {auth,db,action} from '../firebase';
import type {Lang} from '../i18n';
import {labels,statusLabel} from '../admin/i18n';
import {updateOrder,type Data} from './client';
import {paymentState} from './domain.mjs';
export function OrderCard({id,lang,partner=false,onClose}:{id:string;lang:Lang;partner?:boolean;onClose?:()=>void}){
 const t=labels(lang),[order,setOrder]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[quote,setQuote]=useState(''),[reported,setReported]=useState(false);
 useEffect(()=>{setOrder(null);setError('');setReported(false);return onSnapshot(doc(db,'serviceOrders',id),d=>{setOrder(d.exists()?{id:d.id,...d.data()}:null);setError(d.exists()?'':t.empty)},()=>setError(t.dataError))},[id,lang]);
 async function run(kind:string,data:Data={}){if(!auth.currentUser||busy)return;setBusy(true);setError('');try{await updateOrder(db,auth.currentUser,id,kind,data)}catch(e){const msg=String((e as Error).message);setError(msg==='customer-confirmation-required'?(lang==='ru'?'Нужно подтверждение цены и посадки клиента.':lang==='tg'?'Тасдиқи нарх ва саворшавии муштарӣ лозим.':'Mijoz narxni va kelganingizni tasdiqlashi kerak.'):msg==='price-changed'?(lang==='ru'?'Цена изменилась. Проверьте новую цену.':lang==='tg'?'Нарх тағйир ёфт. Нархи навро санҷед.':'Narx o‘zgardi. Yangi narxni tekshiring.'):msg==='permission-denied'?t.permission:t.dataError)}finally{setBusy(false)}}
 if(!order)return <section className="spark-card"><p role="status">{error||t.loading}</p></section>;const o=order,ended=['completed','cancelled'].includes(o.status);
 return <section className="spark-card order-live" aria-live="polite"><div className="spark-heading"><h3>{t.orders}</h3><span className={'spark-status status-'+o.status}>{statusLabel(o.status,lang)}</span></div><p className="spark-id">#{id.slice(0,10)}</p><div className="spark-route"><b>A</b><span>{o.pickup?.name}</span></div>{o.destination&&<div className="spark-route"><b>B</b><span>{o.destination.name}</span></div>}
 {o.providerId&&<div className="spark-contact"><strong>{partner?o.customerName:o.providerName}</strong><a href={'tel:'+(partner?o.customerPhone:o.providerPhone)}>{partner?o.customerPhone:o.providerPhone}</a></div>}{o.notes&&<p>{o.notes}</p>}
 {!o.providerId&&<p>{lang==='ru'?'Ищем свободного водителя. Заказ будет принят автоматически.':lang==='tg'?'Ронандаи озодро ҷустуҷӯ мекунем. Фармоиш худкор қабул мешавад.':'Bo‘sh haydovchi qidirilmoqda. Haydovchi buyurtmani o‘zi qabul qiladi.'}</p>}
 {o.quoteMinor&&<div className="spark-price"><span>{t.quote}</span><strong>{(o.quoteMinor/100).toFixed(2)} TJS</strong><small>{o.quoteAccepted?statusLabel('approved',lang):t.waiting}</small></div>}
 {partner&&!ended&&!o.quoteAccepted&&<form className="spark-quote" onSubmit={e=>{e.preventDefault();run('quote',{quoteMinor:Math.round(Number(quote)*100)})}}><label>{t.quote} · TJS<input required type="number" min="0.01" max="100000" step="0.01" value={quote} onChange={e=>setQuote(e.target.value)}/></label><button disabled={busy}>{t.save}</button></form>}
 {!partner&&!ended&&o.quoteMinor&&!o.quoteAccepted&&<button disabled={busy} onClick={()=>run('acceptQuote',{quoteMinor:o.quoteMinor})}>{lang==='ru'?'Подтвердить цену':lang==='tg'?'Тасдиқи нарх':'Narxni tasdiqlash'} · {(o.quoteMinor/100).toFixed(2)} TJS</button>}
 {!partner&&o.status==='arrived'&&o.quoteAccepted&&!o.pickupConfirmed&&<button disabled={busy} onClick={()=>run('confirmPickup')}>{lang==='ru'?'Я с водителем / исполнителем':lang==='tg'?'Ман бо ронанда / иҷрокунанда ҳастам':'Haydovchi / ijrochi yonimdaman'}</button>}
 {partner&&!ended&&<button disabled={busy||(o.status==='arrived'&&(!o.pickupConfirmed||!o.quoteAccepted))} onClick={()=>run('status',{status:({accepted:'arriving',arriving:'arrived',arrived:'in_progress',in_progress:'completed'} as Data)[o.status]})}>{statusLabel(({accepted:'arriving',arriving:'arrived',arrived:'in_progress',in_progress:'completed'} as Data)[o.status],lang)}</button>}
 {o.status==='completed'&&<><p>{t.payment}: {statusLabel(paymentState(o),lang)}</p>{!partner&&!o.paymentReported&&<button disabled={busy} onClick={()=>run('reportPayment')}>{lang==='ru'?'Я оплатил':lang==='tg'?'Ман пардохт кардам':'To‘ladim'}</button>}{partner&&o.paymentReported&&!o.paymentConfirmed&&<button disabled={busy} onClick={()=>run('confirmPayment')}>{lang==='ru'?'Оплата получена':lang==='tg'?'Пардохт гирифта шуд':'To‘lovni oldim'}</button>}</>}
 {!ended&&o.status!=='in_progress'&&<details className="spark-cancel"><summary>{t.cancel}</summary><label>{t.reason}<input maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="spark-danger" disabled={busy||!reason.trim()} onClick={()=>run('status',{status:'cancelled',reason})}>{t.cancel}</button></details>}
 <details className="spark-cancel"><summary>{t.complaints}</summary>{reported?<p>{lang==='ru'?'Жалоба отправлена.':lang==='tg'?'Шикоят фиристода шуд.':'Shikoyat yuborildi.'}</p>:<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await action({kind:'reportOrder',orderId:id,subject:f.get('subject'),description:f.get('description')});setReported(true)}catch{setError(t.dataError)}finally{setBusy(false)}}}><label>{t.name}<input name="subject" required maxLength={80}/></label><label>{t.description}<textarea name="description" required maxLength={2000}/></label><button disabled={busy}>{t.save}</button></form>}</details>{error&&<p role="alert" className="spark-error">{error}</p>}
 {ended&&onClose&&<button style={{marginTop:18}} disabled={busy} onClick={onClose}>{t.close}</button>}</section>;
}
