import React,{useEffect,useRef,useState,createContext,useContext} from 'react';
import {createRoot} from 'react-dom/client';
import {onAuthStateChanged,signInWithEmailAndPassword,signOut,sendPasswordResetEmail,type User} from 'firebase/auth';
import {collection,doc,query,where,orderBy,limit,startAfter,onSnapshot,getCountFromServer,Timestamp,type QueryConstraint,type QueryDocumentSnapshot} from 'firebase/firestore';
import {auth,db} from '../firebase';
import {Icon} from '../ui';
import type {Lang} from '../i18n';
import {labels,statusLabel} from './i18n';
import {adminAccess,type Data} from '../spark/client';
import {adminMutation,moderateProvider} from '../spark/admin-data';
import {dataToCsv,paymentState} from '../spark/domain.mjs';
import './style.css';
type Section='dashboard'|'orders'|'users'|'providers'|'drivers'|'technicians'|'jobs'|'complaints'|'organizations'|'cities'|'categories'|'tariffs'|'settings'|'audit';
const sections:Section[]=['dashboard','orders','users','providers','drivers','technicians','jobs','complaints','organizations','cities','categories','tariffs','settings','audit'];
const names:Record<string,string>={orders:'serviceOrders',users:'users',providers:'providerApplications',drivers:'driverProfiles',technicians:'technicianProfiles',jobs:'jobPosts',complaints:'complaints',organizations:'organizations',cities:'cities',categories:'categories',tariffs:'tariffs',audit:'auditLogs'};
const icons:Record<string,string>={dashboard:'home',orders:'delivery',users:'profile',providers:'shield',drivers:'taxi',technicians:'services',jobs:'jobs',complaints:'support',organizations:'jobs',cities:'pin',categories:'filter',tariffs:'card',settings:'filter',audit:'clock'};
const filterOptions:Record<string,string[]>={orders:['requested','accepted','arriving','arrived','in_progress','completed','cancelled'],providers:['pending','approved','rejected','suspended'],drivers:['approved','suspended'],technicians:['approved','suspended'],jobs:['pending_review','published','closed','rejected'],complaints:['open','investigating','resolved','dismissed'],organizations:['approved','pending','suspended']};
const currentSection=()=>sections.includes(location.hash.slice(1) as Section)?location.hash.slice(1) as Section:'dashboard';
const localPreview=new URLSearchParams(location.search).get('preview')==='1'&&['localhost','127.0.0.1','[::1]'].includes(location.hostname);
const formatDate=(v:any,lang:Lang)=>v?.seconds?new Intl.DateTimeFormat(lang==='uz'?'uz-UZ':lang==='ru'?'ru-RU':'tg-TJ',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Dushanbe'}).format(new Date(v.seconds*1000)):'—';
const money=(v:any)=>Number.isInteger(v)?(v/100).toFixed(2)+' TJS':'—';
function problem(e:unknown,lang:Lang){const c=String((e as any)?.code||(e as any)?.message||'');const m:Record<string,[string,string,string]>={'permission-denied':['Ҳуқуқ ё қоидаҳои база мувофиқ нестанд.','Недостаточно прав или правила базы не установлены.','Huquqlar yetarli emas yoki baza qoidalari o‘rnatilmagan.'],'failed-precondition':['Индекси база лозим аст.','Нужен индекс базы.','Baza indeksi kerak.'],'resource-exhausted':['Маҳдудияти ройгон анҷом ёфт.','Достигнут бесплатный лимит.','Bepul limitga yetildi.'],'record-changed':['Сабт тағйир ёфт. Аз нав кушоед.','Запись изменилась. Откройте её снова.','Yozuv o‘zgardi. Qayta oching.'],'provider-phone-required':['Телефони шарик дар ариза нест.','В заявке нет телефона партнёра.','Hamkor arizasida telefon yo‘q.']};return m[c]?.[{tg:0,ru:1,uz:2}[lang]]||labels(lang).dataError;}
type Context={user:User|null;lang:Lang;t:ReturnType<typeof labels>;preview:boolean;busy:boolean;act:(fn:()=>Promise<unknown>)=>Promise<boolean>};
const AppContext=createContext<Context>(null!);const ctx=()=>useContext(AppContext);
function Badge({value}:{value:string}){const{lang,t}=ctx();return <span className={'badge state-'+value}>{value==='active'?t.active:value==='inactive'?t.inactive:statusLabel(value,lang)}</span>}
function Empty({loading=false}:{loading?:boolean}){const{t}=ctx();return <div className="empty-state">{loading?<span className="spinner"/>:<div className="empty-symbol"><Icon name="jobs"/></div>}<strong>{loading?t.loading:t.empty}</strong>{!loading&&<p>{t.emptyText}</p>}</div>}
function App(){
 const[lang,setLang]=useState<Lang>(()=>{try{return ['tg','ru','uz'].includes(localStorage.getItem('cavi-admin-lang')||'')?localStorage.getItem('cavi-admin-lang') as Lang:'uz'}catch{return 'uz'}}),[user,setUser]=useState<User|null>(null),[access,setAccess]=useState<'loading'|'allowed'|'denied'|'error'>('loading'),[section,setSection]=useState<Section>(currentSection),[drawer,setDrawer]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[online,setOnline]=useState(navigator.onLine),[generation,setGeneration]=useState(0);
 const t=labels(lang),running=useRef(false);
 useEffect(()=>{const f=()=>{setSection(currentSection());setDrawer(false);setError('');setMessage('')};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);
 useEffect(()=>{document.documentElement.lang=lang;try{localStorage.setItem('cavi-admin-lang',lang)}catch{}},[lang]);
 useEffect(()=>{if(localPreview){setAccess('allowed');return}let alive=true;const off=onAuthStateChanged(auth,async u=>{setUser(u);setAccess('loading');if(!u){setAccess('denied');return}try{const ok=await adminAccess(db,u);if(alive)setAccess(ok?'allowed':'denied')}catch(e){if(alive){setAccess('error');setError(problem(e,lang))}}});return()=>{alive=false;off()}},[generation]);
 useEffect(()=>{const f=()=>setOnline(navigator.onLine);addEventListener('online',f);addEventListener('offline',f);return()=>{removeEventListener('online',f);removeEventListener('offline',f)}},[]);
 async function act(fn:()=>Promise<unknown>){if(localPreview||running.current)return false;running.current=true;setBusy(true);setError('');setMessage('');try{await fn();setMessage(t.saved);return true}catch(e){setError(problem(e,lang));return false}finally{running.current=false;setBusy(false)}}
 const value={user,lang,t,preview:localPreview,busy,act};
 function nav(s:Section){location.hash=s;setSection(s);setDrawer(false)}
 return <AppContext.Provider value={value}>{access==='loading'?<div className="gate"><span className="spinner"/><p>{t.accessLoading}</p></div>:access!=='allowed'?<div className="gate"><div className="gate-brand">Cavi <span>Go</span><small>ADMIN</small></div><Language value={lang} change={setLang}/>{user?<div className="gate-card"><Icon name="shield"/><h1>{access==='error'?t.dataError:t.permission}</h1><p>{t.permissionText}</p>{error&&<p role="alert" className="notice error">{error}</p>}<button onClick={()=>setGeneration(v=>v+1)}>{t.retry}</button><button className="secondary" onClick={()=>signOut(auth)}>{t.logout}</button></div>:<Login lang={lang}/>}<a href="/">← {t.customerSite}</a></div>:<div className="admin-shell">
  {drawer&&<button className="drawer-scrim" aria-label={t.close} onClick={()=>setDrawer(false)}/>}
  <aside className={drawer?'sidebar open':'sidebar'}><a className="brand" href="#dashboard">Cavi <span>Go</span><small>CONTROL CENTER</small></a><div className="sidebar-label">CAPLINE GROUP · DUSHANBE</div><nav aria-label="Admin">{sections.slice(0,9).map(s=><button key={s} aria-current={section===s?'page':undefined} onClick={()=>nav(s)}><Icon name={icons[s]}/>{t[s]}<span>›</span></button>)}<div className="sidebar-label">CAVI GO</div>{sections.slice(9).map(s=><button key={s} aria-current={section===s?'page':undefined} onClick={()=>nav(s)}><Icon name={icons[s]}/>{t[s]}</button>)}</nav><div className="sidebar-bottom"><div className="avatar">{user?.displayName?.slice(0,1)||'A'}</div><div><strong>{user?.displayName||'Admin'}</strong><small>{user?.email||t.preview}</small></div><button aria-label={t.logout} disabled={localPreview} onClick={()=>signOut(auth)}><Icon name="logout"/></button></div></aside>
  <div className="workspace"><header className="topbar"><div className="topbar-left"><button className="mobile-menu icon-button" aria-label="Menu" onClick={()=>setDrawer(!drawer)}><Icon name="filter"/></button><span className="breadcrumb">Cavi Go <span>/</span> <b>{t[section]}</b></span></div><div className="topbar-actions"><a className="site-link" href="/">{t.customerSite} ↗</a><Language value={lang} change={setLang}/><div className={'connection '+(online?'':'offline')}><i/>{online?'ONLINE':t.offline}</div></div></header>
  <main><div className="page-title"><div><p className="eyebrow">CAVI GO · ADMIN</p><h1>{t[section]}</h1><p>{section==='dashboard'?t.automaticText:section==='orders'?t.automaticText:section==='audit'?t.noFake:t.scope}</p></div><div className="title-actions"><button className="secondary" onClick={()=>setGeneration(v=>v+1)}><Icon name="clock"/>{t.refresh}</button></div></div>
   {localPreview&&<div className="notice preview"><Icon name="info"/><div><b>{t.preview}</b><p>{t.previewText}</p></div></div>}
   {!online&&<div className="notice error" role="alert">{t.offline}</div>}{error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError('')} aria-label={t.close}>×</button></div>}{message&&<div role="status" className="notice success">{message}<button onClick={()=>setMessage('')} aria-label={t.close}>×</button></div>}
   {section==='dashboard'?<Dashboard key={generation} nav={nav}/>:section==='settings'?<Settings key={generation}/>:<Records key={section+generation} section={section}/>}
  </main><footer>© {new Date().getFullYear()} Cavi Go · Capline Group <span>Spark · TJS · Asia/Dushanbe</span></footer></div>
 </div>}</AppContext.Provider>
}
function Language({value,change}:{value:Lang;change:(v:Lang)=>void}){return <select aria-label="Language" value={value} onChange={e=>change(e.target.value as Lang)}><option value="uz">O‘zbekcha</option><option value="ru">Русский</option><option value="tg">Тоҷикӣ</option></select>}
function Login({lang}:{lang:Lang}){const t=labels(lang),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[email,setEmail]=useState('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const f=new FormData(e.currentTarget);await signInWithEmailAndPassword(auth,email,String(f.get('password')))}catch{setError(t.authError)}finally{setBusy(false)}}return <section className="gate-card"><div className="gate-icon"><Icon name="shield"/></div><h1>{t.login}</h1><p>{t.ownerSetup}</p><form onSubmit={submit}><label>{t.email}<input name="email" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{t.password}<input name="password" type="password" autoComplete="current-password" required minLength={8}/></label>{error&&<p role="alert" className="notice error">{error}</p>}{notice&&<p role="status">{notice}</p>}<button disabled={busy}>{busy?t.loading:t.enter}</button></form><button className="text-button" disabled={!email||busy} onClick={async()=>{setBusy(true);try{await sendPasswordResetEmail(auth,email);setNotice(lang==='ru'?'Если аккаунт существует, письмо отправлено.':lang==='tg'?'Агар ҳисоб мавҷуд бошад, мактуб фиристода шуд.':'Hisob mavjud bo‘lsa, tiklash xati yuborildi.')}catch{setError(t.authError)}finally{setBusy(false)}}}>{lang==='ru'?'Забыли пароль?':lang==='tg'?'Рамзро фаромӯш кардед?':'Parolni unutdingizmi?'}</button></section>}
function Dashboard({nav}:{nav:(s:Section)=>void}){const{preview,t,lang}=ctx(),[stats,setStats]=useState<Record<string,number|null>>({}),[error,setError]=useState(''),[platform,setPlatform]=useState<Data|null>(null),[period,setPeriod]=useState(30);
 useEffect(()=>{if(preview)return;let alive=true;setStats({});setError('');const zoned=new Date(Date.now()+5*3600000);const since=Timestamp.fromDate(period===1?new Date(Date.UTC(zoned.getUTCFullYear(),zoned.getUTCMonth(),zoned.getUTCDate())-5*3600000):new Date(Date.now()-period*86400000));const jobs:{key:string;q:ReturnType<typeof query>}[]=[{key:'users',q:query(collection(db,'users'))},{key:'orders',q:query(collection(db,'serviceOrders'),where('createdAt','>=',since))},{key:'providers',q:query(collection(db,'providerApplications'),where('status','==','pending'))},{key:'jobs',q:query(collection(db,'jobPosts'),where('status','==','pending_review'))},{key:'complaints',q:query(collection(db,'complaints'),where('status','==','open'))},{key:'drivers',q:query(collection(db,'driverProfiles'),where('status','==','approved'))}];Promise.allSettled(jobs.map(async({key,q})=>{const r=await getCountFromServer(q);if(alive)setStats(p=>({...p,[key]:r.data().count}))})).then(r=>{if(alive&&r.some(x=>x.status==='rejected'))setError(t.countError)});const off=onSnapshot(doc(db,'settings','platform'),d=>setPlatform(d.exists()?d.data():null),()=>{});return()=>{alive=false;off()}},[period]);
 const tiles:[string,string,string][]=[['orders',t.orders,'delivery'],['users',t.accounts,'profile'],['drivers',t.profiles,'taxi'],['providers',t.providers,'shield']];return <>
 <div className="dashboard-toolbar"><span>{t.noFake}</span><select aria-label={t.window} value={period} onChange={e=>setPeriod(Number(e.target.value))}><option value={1}>{t.today}</option><option value={7}>{t.week}</option><option value={30}>{t.month}</option></select></div>
 {error&&<div role="alert" className="notice error">{error}</div>}<div className="stats-grid">{tiles.map(([key,title,icon])=><button className="stat-card" onClick={()=>nav(key as Section)} key={key}><div><span>{title}</span><Icon name={icon}/></div><strong>{stats[key]??'—'}</strong><small>{key==='orders'?`${period} ${lang==='ru'?'дней':lang==='tg'?'рӯз':'kun'}`:key==='users'?t.accounts:key==='drivers'?t.drivers:t.waiting}<span>↗</span></small></button>)}</div>
 <div className="dashboard-columns"><section className="panel"><div className="panel-heading"><h2>{t.recent}</h2><button className="text-button" onClick={()=>nav('orders')}>{t.all} →</button></div><Records section="orders" compact/></section><div className="dashboard-side"><section className="panel review-panel"><h2>{t.reviewQueue}</h2>{(['providers','jobs','complaints'] as Section[]).map(key=><button key={key} onClick={()=>nav(key)}><span className="review-icon"><Icon name={icons[key]}/></span><div><strong>{t[key]}</strong><small>{t.waiting}</small></div><b>{stats[key]??'—'}</b><span>›</span></button>)}</section><section className="automatic-card"><div className="automatic-top"><Icon name="shield"/><span className={'badge '+(platform?.ordersEnabled?'state-approved':'state-pending')}>{platform?.ordersEnabled?t.enabled:t.pause}</span></div><h2>{t.automatic}</h2><p>{t.automaticText}</p><button onClick={()=>nav('settings')}>{t.settings} →</button></section></div></div>
 <div className="info-grid"><section className="panel mini-info"><Icon name="card"/><h3>{t.mode}</h3><p>{t.cashText}</p></section><section className="panel mini-info"><Icon name="info"/><h3>{t.limits}</h3><p>{t.limitsText}</p><a href="https://firebase.google.com/pricing" target="_blank" rel="noreferrer">Firebase ↗</a></section></div>
 </>}
function Records({section,compact=false}:{section:Section;compact?:boolean}){const{preview,t,lang}=ctx(),[rows,setRows]=useState<Data[]>([]),[loading,setLoading]=useState(!preview),[error,setError]=useState(''),[status,setStatus]=useState('all'),[search,setSearch]=useState(''),[service,setService]=useState('all'),[cursor,setCursor]=useState<QueryDocumentSnapshot|null>(null),[history,setHistory]=useState<(QueryDocumentSnapshot|null)[]>([]),[last,setLast]=useState<QueryDocumentSnapshot|null>(null),[hasMore,setHasMore]=useState(false),[selected,setSelected]=useState<Data|null>(null),[edit,setEdit]=useState<Data|null>(null),[tick,setTick]=useState(0);
 const size=compact?6:25;
 useEffect(()=>{setRows([]);setError('');if(preview){setLoading(false);return}setLoading(true);const constraints:QueryConstraint[]=[];if(status!=='all')constraints.push(where('status','==',status));if(service!=='all')constraints.push(where('serviceType','==',service));constraints.push(orderBy('createdAt','desc'));if(cursor)constraints.push(startAfter(cursor));constraints.push(limit(size+1));return onSnapshot(query(collection(db,names[section]),...constraints),s=>{setRows(s.docs.slice(0,size).map(d=>({id:d.id,...d.data()})));setHasMore(s.size>size);setLast(s.docs[Math.min(size,s.size)-1]||null);setLoading(false)},e=>{setRows([]);setError(problem(e,lang));setLoading(false)})},[section,status,service,cursor,tick]);
 function reset(){setCursor(null);setHistory([])}
 const visible=rows.filter(r=>[r.id,r.name,r.title,r.company,r.customerName,r.providerName,r.description,r.subject,r.action,r.targetPath].some(v=>String(v||'').toLocaleLowerCase().includes(search.toLocaleLowerCase())));
 const canAdd=['cities','categories','tariffs'].includes(section);
 function exportRows(){const keys=section==='orders'?['id','serviceType','status','cityId','quoteMinor','currency']:section==='audit'?['id','actorId','action','targetPath','reason','version']:['id','name','title','status','city','category'];const a=document.createElement('a'),url=URL.createObjectURL(new Blob([dataToCsv(visible,keys)],{type:'text/csv;charset=utf-8'}));a.href=url;a.download=`cavi-${section}-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <div className={compact?'records compact':'panel records'}>{!compact&&<div className="records-toolbar"><label className="search-field"><Icon name="search"/><input placeholder={t.search} aria-label={t.search} value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="filter-actions">{filterOptions[section]&&<select aria-label={t.status} value={status} onChange={e=>{setStatus(e.target.value);reset()}}><option value="all">{t.all}</option>{filterOptions[section].map(v=><option key={v} value={v}>{statusLabel(v,lang)}</option>)}</select>}{section==='orders'&&<select aria-label={t.service} value={service} onChange={e=>{setService(e.target.value);reset()}}><option value="all">{t.all}</option>{['taxi','master','delivery'].map(s=><option value={s} key={s}>{t[s as 'taxi'|'master'|'delivery']}</option>)}</select>}<button className="secondary" disabled={!visible.length} onClick={exportRows}><Icon name="jobs"/>{t.export}</button>{canAdd&&<button disabled={preview} onClick={()=>setEdit({})}>+ {t.add}</button>}</div></div>}
 {error?<div className="empty-state"><Icon name="info"/><p role="alert">{error}</p><button onClick={()=>setTick(v=>v+1)}>{t.retry}</button></div>:loading?<Empty loading/>:!visible.length?<Empty/>:<div className="table-wrap"><table><thead><tr><th>{t.id}</th><th>{section==='orders'?t.customer:section==='audit'?t.role:t.name}</th><th>{section==='audit'?t.reason:t.status}</th><th>{t.date}</th><th aria-label={t.detail}/></tr></thead><tbody>{visible.map(row=><tr key={row.id}><td><button className="id-link" onClick={()=>setSelected(row)}>{row.id.length>14?row.id.slice(0,10)+'…':row.id}</button><small>{row.serviceType?t[row.serviceType as 'taxi'|'master'|'delivery']:row.category||row.role||''}</small></td><td><strong>{row.customerName||row.name||row.title||row.action||row.subject||row.id}</strong><small>{row.providerName||row.company||row.city||row.targetPath||''}</small></td><td>{section==='audit'?<span className="reason-text">{row.reason}</span>:row.blocked?<Badge value="suspended"/>:<Badge value={row.status||('active'in row?(row.active?'active':'inactive'):'active')}/>}</td><td className="date-cell">{formatDate(row.createdAt,lang)}</td><td><button className="icon-button row-open" aria-label={t.detail+' '+row.id} onClick={()=>setSelected(row)}>↗</button></td></tr>)}</tbody></table></div>}
 {!compact&&<div className="pagination"><span>{t.scope} · {visible.length}{hasMore?' +':''}</span><div><button className="secondary" disabled={!history.length||loading} onClick={()=>{setCursor(history[history.length-1]);setHistory(h=>h.slice(0,-1))}}>← {t.back}</button><button className="secondary" disabled={!hasMore||loading} onClick={()=>{setHistory(h=>[...h,cursor]);setCursor(last)}}>{t.more} →</button></div></div>}
 {selected&&<Details section={section} record={selected} close={()=>setSelected(null)} edit={()=>{setEdit(selected);setSelected(null)}}/>}{edit&&<EntityEditor section={section} record={edit} close={()=>setEdit(null)}/>}
 </div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){const{t}=ctx(),ref=useRef<HTMLElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.focus();const f=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const els=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href]')||[]).filter(x=>x.offsetParent!==null);const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};addEventListener('keydown',f);return()=>{removeEventListener('keydown',f);previous?.focus()}},[]);return <div className="modal-backdrop" onClick={close}><section tabIndex={-1} ref={ref} role="dialog" aria-modal="true" aria-label={title} className="modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>{title}</h2><button className="icon-button" aria-label={t.close} onClick={close}>×</button></div>{children}</section></div>}
function Details({section,record,close,edit}:{section:Section;record:Data;close:()=>void;edit:()=>void}){const{user,t,lang,act,busy,preview}=ctx(),[reason,setReason]=useState(''),[current,setCurrent]=useState(record),[events,setEvents]=useState<Data[]>([]),[detailError,setDetailError]=useState('');useEffect(()=>{if(preview)return;const off=onSnapshot(doc(db,names[section],record.id),d=>{if(d.exists())setCurrent({id:d.id,...d.data()})},e=>setDetailError(problem(e,lang)));let eventOff=()=>{};if(section==='orders')eventOff=onSnapshot(query(collection(db,'serviceOrders',record.id,'events'),orderBy('createdAt','desc'),limit(50)),s=>setEvents(s.docs.map(d=>({id:d.id,...d.data()}))),e=>setDetailError(problem(e,lang)));return()=>{off();eventOff()}},[]);
 const r=current;async function mutate(patch:Data){if(await act(()=>adminMutation(db,user!,names[section]+'/'+r.id,patch,reason,r.version)))close()};
 const fields:[string,any][]=[[t.id,r.id],[t.name,r.name||r.title||r.customerName],[t.role,r.role||r.serviceType],[t.city,r.city||r.cityId],[t.phone,r.phone||r.customerPhone],[t.email,r.email],[t.customer,r.customerId],[t.provider,r.providerName||r.providerId],[t.phone+' · '+t.provider,r.providerPhone],[t.description,r.description||r.skills],[t.notes,r.notes],[t.reason,r.reason||r.moderationReason||r.blockedReason||r.resolution],[t.version,r.version],[t.date,formatDate(r.createdAt,lang)]];
 return <Modal title={t.detailsTitle} close={close}><div className="detail-heading"><div className="detail-avatar"><Icon name={icons[section]}/></div><div><h3>{r.name||r.title||r.customerName||r.subject||r.action||r.id}</h3><Badge value={r.status||'active'}/></div></div>{detailError&&<p role="alert" className="notice error">{detailError}</p>}<dl className="details-grid">{fields.filter(([,v])=>v!==undefined&&v!==null&&v!=='').map(([name,value],i)=><div key={name+i}><dt>{name}</dt><dd>{String(value)}</dd></div>)}</dl>
 {section==='orders'&&<><div className="route-card"><Icon name="pin"/><div><b>{r.pickup?.name||'—'}</b><small>{r.destination?.name||'—'}</small></div></div><dl className="details-grid"><div><dt>{t.quote}</dt><dd>{money(r.quoteMinor)}</dd></div><div><dt>{t.payment}</dt><dd>{statusLabel(paymentState(r),lang)}</dd></div></dl><h3>{t.eventHistory}</h3><div className="timeline">{events.map(e=><div key={e.id}><i/><div><b>{statusLabel(e.action,lang)}</b><small>{formatDate(e.createdAt,lang)} · {e.actorId}</small>{e.reason&&<p>{e.reason}</p>}</div></div>)}{!events.length&&<p>{t.empty}</p>}</div></>}
 {['providers','jobs','users','complaints','organizations'].includes(section)&&<div className="mutation-box"><label>{section==='complaints'?t.resolution:t.reason}<textarea required maxLength={500} placeholder={t.reasonPlaceholder} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="mutation-actions">
 {section==='providers'&&[['approved',t.approve],['rejected',t.reject],['suspended',t.suspend]].map(([state,label])=><button className={state==='approved'?'':'secondary'} key={state} disabled={!reason.trim()||busy||preview||r.status===state} onClick={async()=>{if(await act(()=>moderateProvider(db,user!,r.id,state,reason,r.version)))close()}}>{label}</button>)}
 {section==='jobs'&&[['published',t.publish],['rejected',t.reject],['closed',t.close]].map(([state,label])=><button key={state} className={state==='published'?'':'secondary'} disabled={!reason.trim()||busy||preview||r.status===state} onClick={()=>mutate({status:state,moderationReason:reason})}>{label}</button>)}
 {section==='users'&&<button className={r.blocked?'':'danger'} disabled={!reason.trim()||busy||preview||r.id===user?.uid} onClick={()=>mutate({blocked:!r.blocked,blockedReason:reason})}>{r.blocked?t.unblock:t.block}</button>}
 {section==='complaints'&&[['investigating',t.investigate],['resolved',t.resolve],['dismissed',t.dismiss]].map(([state,label])=><button key={state} disabled={!reason.trim()||busy||preview} onClick={()=>mutate({status:state,resolution:reason})}>{label}</button>)}
 {section==='organizations'&&[['approved',t.approve],['suspended',t.suspend],['rejected',t.reject]].map(([state,label])=><button key={state} disabled={!reason.trim()||busy||preview} onClick={()=>mutate({status:state,reason})}>{label}</button>)}
 </div></div>}
 {['cities','categories','tariffs'].includes(section)&&<button disabled={preview} onClick={edit}>{t.settings}</button>}
 </Modal>}
function EntityEditor({section,record,close}:{section:Section;record:Data;close:()=>void}){const{user,t,act,busy}=ctx(),[error,setError]=useState('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),id=record.id||String(f.get('id'));if(!/^[a-z0-9_-]{1,60}$/.test(id)){setError('ID: a-z, 0-9, _ , -');return}const patch:Data={name:String(f.get('name')).trim(),active:f.get('active')==='on'};if(section==='cities')patch.timezone=String(f.get('timezone'));if(section==='categories')patch.serviceType=String(f.get('serviceType'));if(section==='tariffs'){patch.cityId='dushanbe';patch.category=String(f.get('category'));patch.currency='TJS';for(const k of ['baseMinor','perKmMinor','minimumMinor']){patch[k]=Math.round(Number(f.get(k))*100);if(!Number.isSafeInteger(patch[k])||patch[k]<0||patch[k]>10000000){setError(t.dataError);return}}}if(await act(()=>adminMutation(db,user!,names[section]+'/'+id,patch,String(f.get('reason')),record.id?record.version:0)))close()}return <Modal title={record.id?t.settings:t.add} close={close}><form onSubmit={submit}>{!record.id&&<label>ID<input name="id" required pattern="[a-z0-9_-]{1,60}" maxLength={60}/></label>}<label>{t.name}<input name="name" defaultValue={record.name||''} required maxLength={80}/></label>{section==='cities'&&<label>{t.timezone}<input name="timezone" defaultValue={record.timezone||'Asia/Dushanbe'} required maxLength={80}/></label>}{section==='categories'&&<label>{t.service}<select name="serviceType" defaultValue={record.serviceType||'master'}>{['taxi','master','delivery','jobs'].map(s=><option key={s} value={s}>{t[s as 'taxi'|'master'|'delivery'|'jobs']}</option>)}</select></label>}{section==='tariffs'&&<><p>{t.tariffNote}</p><label>{t.categories}<input name="category" required defaultValue={record.category||'economy'} maxLength={40}/></label>{[['baseMinor',t.base],['perKmMinor',t.perKm],['minimumMinor',t.minimum]].map(([key,label])=><label key={key}>{label}<input type="number" name={key} required step="0.01" min={0} max={100000} defaultValue={(record[key]||0)/100}/></label>)}</>}<label className="check-label"><input type="checkbox" name="active" defaultChecked={record.active??true}/>{t.active}</label><label>{t.reason}<textarea name="reason" required minLength={3} maxLength={500}/></label>{error&&<p role="alert" className="notice error">{error}</p>}<div className="modal-footer"><button type="button" className="secondary" onClick={close}>{t.cancel}</button><button disabled={busy}>{t.save}</button></div></form></Modal>}
function Settings(){const{preview,user,t,act,busy}=ctx(),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(!preview);useEffect(()=>{if(preview)return;return onSnapshot(doc(db,'settings','platform'),d=>{setData(d.exists()?d.data():null);setLoading(false)},e=>{setError(problem(e,'uz'));setLoading(false)})},[]);async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await act(()=>adminMutation(db,user!,'settings/platform',{ordersEnabled:f.get('ordersEnabled')==='on',services:{taxi:f.get('taxi')==='on',master:f.get('master')==='on',delivery:f.get('delivery')==='on'},cityId:'dushanbe',supportEmail:String(f.get('supportEmail')||''),supportPhone:String(f.get('supportPhone')||''),notice:String(f.get('notice')||'')},String(f.get('reason')),data?.version||0))}return <div className="settings-layout"><section className="panel settings-panel"><h2>{t.automatic}</h2><p>{t.automaticText}</p>{error?<p role="alert" className="notice error">{error}</p>:loading?<Empty loading/>:<form key={data?.version||0} onSubmit={save}><label className="switch-label"><div><strong>{t.allowOrders}</strong><small>{t.automaticText}</small></div><input type="checkbox" name="ordersEnabled" defaultChecked={data?.ordersEnabled||false}/></label><h3>{t.enabledServices}</h3><div className="service-switches">{['taxi','master','delivery'].map(s=><label key={s}><Icon name={s==='master'?'services':s}/><span>{t[s as 'taxi'|'master'|'delivery']}</span><input type="checkbox" name={s} defaultChecked={data?.services?.[s]||false}/></label>)}</div><h3>{t.support}</h3><div className="form-grid"><label>{t.email}<input name="supportEmail" type="email" maxLength={160} defaultValue={data?.supportEmail||''}/></label><label>{t.phone}<input name="supportPhone" type="tel" maxLength={30} defaultValue={data?.supportPhone||''}/></label></div><label>{t.notice}<textarea name="notice" maxLength={1000} defaultValue={data?.notice||''}/></label><label>{t.reason}<textarea name="reason" required maxLength={500} placeholder={t.reasonPlaceholder}/></label><button disabled={busy||preview}>{t.save}</button></form>}</section><aside className="settings-side"><section className="panel mini-info"><Icon name="card"/><h3>{t.mode}</h3><p>{t.cashText}</p></section><section className="panel mini-info"><Icon name="info"/><h3>{t.limits}</h3><p>{t.limitsText}</p><a href="https://firebase.google.com/pricing" target="_blank" rel="noreferrer">Firebase ↗</a></section><section className="panel mini-info"><Icon name="shield"/><h3>{t.audit}</h3><p>{t.saved}</p></section></aside></div>}
createRoot(document.getElementById('root')!).render(<App/>);
