import {useEffect,useRef,useState} from 'react';
import {Marker} from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import {createAtlasGL,baseLabels,type AtlasGL} from './map-engine/atlas-gl';
import {loadPlaces,placeName,placeAddress,type Place} from './places';
import {Icon,say} from './ui';
import type {Lang} from './i18n';
export function Fuel({lang}:{lang:Lang}){
 const node=useRef<HTMLDivElement>(null),engine=useRef<AtlasGL|null>(null),marker=useRef<Marker|null>(null);
 const [places,setPlaces]=useState<Place[]>([]),[q,setQ]=useState(''),[selected,setSelected]=useState<Place|null>(null),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[filter,setFilter]=useState('all');
 useEffect(()=>{let disposed=false;if(!node.current)return;let a:AtlasGL;try{a=createAtlasGL(node.current,()=>{if(!disposed)setFailed(true)})}catch{setFailed(true);setLoading(false);return}engine.current=a;a.map.jumpTo({center:[68.7869,38.5737],zoom:13});
 baseLabels().then(l=>{if(!disposed)a.setLabels(l)}).catch(()=>{});
 loadPlaces().then(p=>{if(disposed)return;const fuel=p.filter(x=>x.tags.amenity==='fuel');setPlaces(fuel);a.ready.then(()=>{if(!disposed)a.setPoints(fuel.map(p=>({id:p.id,lat:p.lat,lon:p.lon,name:placeName(p),category:'fuel',icon:'fuel',rank:0})))}).catch(()=>{if(!disposed)setFailed(true)})}).catch(()=>{if(!disposed)setFailed(true)}).finally(()=>{if(!disposed)setLoading(false)});
 return()=>{disposed=true;marker.current?.remove();a.destroy();engine.current=null}},[]);
 function pick(p:Place){setSelected(p);const a=engine.current;if(!a)return;marker.current?.remove();marker.current=new Marker({color:'#08733f'}).setLngLat([p.lon,p.lat]).addTo(a.map);a.map.easeTo({center:[p.lon,p.lat],zoom:16,offset:[0,-80]})}
 const matches=places.filter(p=>Object.values(p.tags).join(' ').toLocaleLowerCase().includes(q.toLocaleLowerCase())&&(filter==='all'||p.tags['opening_hours']==='24/7')).sort((a,b)=>(a.lat-38.5737)**2+(a.lon-68.7869)**2-((b.lat-38.5737)**2+(b.lon-68.7869)**2));
 return <section className="fuel-page"><div className="page-heading"><div><h1>{say(lang,'Нуқтаҳои сӯзишворӣ','Заправки','Yoqilg‘i shoxobchalari')}</h1><p>{say(lang,'Дар харитаи Cavi нуқтаро интихоб кунед.','Выберите заправку на карте Cavi.','Cavi xaritasidan shoxobchani tanlang.')}</p></div><Icon name="fuel"/></div><div ref={node} className="fuel-map" aria-label="Cavi Maps"/><div className="directory-tools"><label className="search-box"><Icon name="search"/><input aria-label={say(lang,'Ҷустуҷӯи нуқта','Поиск заправок','Shoxobcha qidirish')} placeholder={say(lang,'Ном ё суроға','Название или адрес','Nom yoki manzil')} value={q} onChange={e=>setQ(e.target.value)}/></label><div className="chips"><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>{say(lang,'Ҳама','Все','Barchasi')}</button><button aria-pressed={filter==='24/7'} onClick={()=>setFilter('24/7')}>24/7</button></div></div><p className="data-note">{say(lang,'Маълумоти OpenStreetMap. Нарх ва вақти корро дар нуқта аниқ кунед.','Данные OpenStreetMap. Цены и часы работы уточняйте на заправке.','OpenStreetMap ma’lumotlari. Narx va ish vaqtini shoxobchadan aniqlang.')}</p>{failed&&<p role="alert" className="error">{say(lang,'Харита бор нашуд.','Карта не загрузилась.','Xarita yuklanmadi.')}</p>}{loading?<section className="empty">{say(lang,'Бор шуда истодааст…','Загрузка…','Yuklanmoqda…')}</section>:matches.length?<div className="directory-list">{matches.slice(0,40).map(p=><button className={'directory-card '+(selected?.id===p.id?'selected':'')} key={p.id} onClick={()=>pick(p)}><span className="listing-art"><Icon name="fuel"/></span><span className="listing-body"><strong>{placeName(p)}</strong><small>{placeAddress(p)||`${p.lat.toFixed(4)}, ${p.lon.toFixed(4)}`}</small>{p.tags.opening_hours&&<span className="tag">{p.tags.opening_hours}</span>}</span><Icon name="arrow"/></button>)}</div>:<section className="empty">{say(lang,'Нуқта ёфт нашуд','Ничего не найдено','Shoxobcha topilmadi')}</section>}{selected&&<article className="fuel-detail"><b>{placeName(selected)}</b><p>{placeAddress(selected)}</p>{selected.tags.operator&&<p>{selected.tags.operator}</p>}<button className="light" onClick={()=>{setSelected(null);marker.current?.remove()}}>{say(lang,'Пӯшидан','Закрыть','Yopish')}</button></article>}<p className="data-note">© OpenStreetMap contributors · Cavi Maps</p></section>
}
