import React,{useEffect,useState,Suspense,lazy} from 'react';import{createRoot}from'react-dom/client';
import{onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,updateProfile,User}from'firebase/auth';
import{collection,query,where,limit,onSnapshot}from'firebase/firestore';import{auth,db,action}from'./firebase';import{brand}from'./config';import{text,Lang}from'./i18n';import'./style.css';
type Page='home'|'jobs'|'services'|'taxi'|'profile';type Row={id:string;title?:string;company?:string;description?:string;status?:string;name?:string};
const Taxi=lazy(()=>import('./Taxi').then(m=>({default:m.Taxi})));
function App(){const[lang,setLang]=useState<Lang>('tg'),[page,setPage]=useState<Page>('home'),[user,setUser]=useState<User|null>(null),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<'auth'|'job'|'driver'|null>(null),[register,setRegister]=useState(false);const t=text[lang];
useEffect(()=>{document.documentElement.lang=lang},[lang]);useEffect(()=>onAuthStateChanged(auth,setUser),[]);
useEffect(()=>{setRows([]);setError('');let q;if(page==='jobs')q=query(collection(db,'jobPosts'),where('status','==','published'),limit(20));if(page==='services')q=query(collection(db,'technicianProfiles'),where('status','==','approved'),limit(20));if(page==='profile'&&user)q=query(collection(db,'jobApplications'),where('candidateId','==',user.uid),limit(20));if(!q)return;return onSnapshot(q,s=>setRows(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setError(t.error));},[page,user,lang]);
async function run(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{await fn()}catch{setError(t.error)}finally{setBusy(false)}}
function requireUser(m:'job'|'driver'){setModal(user?m:'auth')}
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{if(modal==='auth'){const email=String(f.get('email')),password=String(f.get('password'));if(register){const c=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(c.user,{displayName:String(f.get('name'))})}else await signInWithEmailAndPassword(auth,email,password);}if(modal==='job')await action({kind:'createJob',title:f.get('title'),company:f.get('company'),description:f.get('description'),city:'Dushanbe'});if(modal==='driver')await action({kind:'providerApplication',role:'driver',name:f.get('name'),vehicle:f.get('vehicle'),plate:f.get('plate')});setModal(null)})}
const icons={home:'◈',jobs:'▤',services:'⌘',taxi:'➜',profile:'○'};
return <><header><a className="logo" href="#" onClick={()=>setPage('home')}>cavi<span>go</span><small>{brand.company}</small></a><div className="top"><span>⌖ {t.city}</span><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="tg">Тоҷикӣ</option><option value="ru">Русский</option><option value="uz">O‘zbekcha</option></select><button className="light" onClick={()=>user?setPage('profile'):setModal('auth')}>{user?.displayName||t.login}</button></div></header>
<main className={page==='taxi'?'taxi-main':''}>{error&&<div role="alert" className="error">{error}</div>}{page==='home'&&<><section className="hero"><div className="eyebrow">CAPLINE GROUP · {t.city.toUpperCase()}</div><h1>{t.title}</h1><p>{t.subtitle}</p><button onClick={()=>setPage('taxi')}>{t.ride} ↗</button><div className="orbit">GO<span>●</span></div></section><div className="cards">{(['jobs','services','taxi']as Page[]).map((p,i)=><button key={p} className={'service-card c'+i} onClick={()=>setPage(p)}><span>{icons[p]}</span><h2>{[t.work,t.craft,t.ride][i]}</h2><p>{t[p]}</p><b>↗</b></button>)}</div><section className="note"><b>{t.city} · Cavi Go</b><p>{t.pending}</p></section></>}
{(page==='jobs'||page==='services')&&<><div className="section-title"><h1>{t[page]}</h1>{page==='jobs'&&<button onClick={()=>requireUser('job')}>{t.publish} +</button>}</div>{rows.length?rows.map(r=><article key={r.id}><div className="eyebrow">{t.city}</div><h2>{r.title||r.name}</h2><p>{r.company}</p><p>{r.description}</p>{page==='jobs'&&<button disabled={busy} onClick={()=>user?run(()=>action({kind:'applyJob',jobId:r.id})):setModal('auth')}>{t.apply}</button>}</article>):<section className="empty"><span>{icons[page]}</span><h2>{t.empty}</h2><p>{t.pending}</p></section>}</>}
{page==='taxi'&&<Suspense fallback={<section className="empty">{t.map}…</section>}><Taxi lang={lang}/></Suspense>}
{page==='profile'&&<><h1>{t.profile}</h1>{user?<><article><h2>{user.displayName||user.email}</h2><p>{user.email}</p><button className="light" onClick={()=>run(()=>signOut(auth))}>{t.logout}</button><button onClick={()=>requireUser('driver')}>{t.driver}</button></article><h2>{t.orders}</h2>{rows.length?rows.map(r=><article key={r.id}>{r.id}<p>{t.status}: {r.status}</p></article>):<p>{t.empty}</p>}</>:<button onClick={()=>setModal('auth')}>{t.login}</button>}</>}
</main><nav>{(['home','jobs','services','taxi','profile']as Page[]).map(p=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}><span>{icons[p]}</span>{t[p]}</button>)}</nav>
{modal&&<div className="overlay" onClick={()=>setModal(null)}><section className="dialog" role="dialog" aria-modal="true" aria-label={modal==='auth'?t.login:modal==='job'?t.publish:t.driver} onClick={e=>e.stopPropagation()}><button className="close light" onClick={()=>setModal(null)} aria-label="Close">×</button><h2>{modal==='auth'?(register?t.register:t.login):modal==='job'?t.publish:t.driver}</h2><form onSubmit={submit}>{modal==='auth'?<>{register&&<label>{t.name}<input name="name" required maxLength={80}/></label>}<label>{t.email}<input name="email" type="email" autoComplete="email" required/></label><label>{t.password}<input name="password" type="password" minLength={8} autoComplete={register?'new-password':'current-password'} required/></label></>:modal==='job'?<><label>{t.titleField}<input name="title" required maxLength={120}/></label><label>{t.company}<input name="company" required maxLength={120}/></label><label>{t.description}<textarea name="description" required maxLength={4000}/></label></>:<><label>{t.name}<input name="name" required maxLength={80}/></label><label>Автомобил<input name="vehicle" required maxLength={80}/></label><label>№<input name="plate" required maxLength={20}/></label></>}<button disabled={busy}>{busy?'…':t.save}</button></form>{modal==='auth'&&<button className="light" onClick={()=>setRegister(!register)}>{register?t.login:t.register}</button>}</section></div>}</>}
createRoot(document.getElementById('root')!).render(<App/>);
