import React,{useEffect,useState,Suspense,lazy} from 'react';
import {createRoot} from 'react-dom/client';
import {onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,updateProfile,sendPasswordResetEmail,type User} from 'firebase/auth';
import {collection,query,where,limit,onSnapshot} from 'firebase/firestore';
import {auth,db,action} from './firebase';
import {brand} from './config';
import {text,type Lang} from './i18n';
import {Icon,ServiceArt,say} from './ui';
import './style.css';

type Page='home'|'jobs'|'services'|'taxi'|'delivery'|'fuel'|'profile';
type Row={id:string;title?:string;company?:string;description?:string;status?:string;name?:string;category?:string;city?:string;salaryMin?:number;salaryMax?:number;experience?:string;employmentType?:string;jobId?:string;createdAt?:{seconds:number}};
type Modal='auth'|'job'|'driver'|'technician'|'info'|'payment'|'addresses'|'language'|'notifications'|'security'|'help'|'about'|'balance'|'promos'|'contact'|null;
const pages:Page[]=['home','jobs','services','taxi','delivery','fuel','profile'];
const Taxi=lazy(()=>import('./Taxi').then(m=>({default:m.Taxi})));
const Fuel=lazy(()=>import('./Fuel').then(m=>({default:m.Fuel})));
const currentPage=():Page=>{const p=location.hash.slice(1) as Page;return pages.includes(p)?p:'home'};
function preferredLanguage():Lang {
 try {const saved=localStorage.getItem('cavi-go-language');if(saved==='tg'||saved==='ru'||saved==='uz')return saved;} catch {}
 return 'tg';
}
function App(){
 const [lang,setLang]=useState<Lang>(preferredLanguage),[page,setPage]=useState<Page>(currentPage),[user,setUser]=useState<User|null>(null),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<Modal>(null),[register,setRegister]=useState(false),[loading,setLoading]=useState(false),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[sort,setSort]=useState('new'),[selected,setSelected]=useState<Row|null>(null),[retry,setRetry]=useState(0),[rowLimit,setRowLimit]=useState(20),[deliveryCategory,setDeliveryCategory]=useState('all');
 const [profileTarget,setProfileTarget]=useState('');
 const t=text[lang];const s=(tg:string,ru:string,uz:string)=>say(lang,tg,ru,uz);
 const pageName=(p:Page)=>p==='delivery'?s('Расонидан','Доставка','Yetkazib berish'):p==='fuel'?s('Сӯзишворӣ','Заправки','Yoqilg‘i'):t[p];
 const tileName=(p:Page)=>p==='fuel'?s('АЗС','Заправки','Yoqilg‘i'):p==='delivery'?s('Расонидан','Доставка','Yetkazish'):pageName(p);
 function go(p:Page){setModal(null);setSelected(null);setSearch('');setCategory('all');setRowLimit(20);setNotice('');setError('');if(location.hash.slice(1)!==p)location.hash=p;else setPage(p);window.scrollTo({top:0,behavior:'instant'})}
 useEffect(()=>{const f=()=>{setPage(currentPage());setSelected(null);setSearch('');setCategory('all');setError('');setNotice('')};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);
 useEffect(()=>{document.documentElement.lang=lang;try{localStorage.setItem('cavi-go-language',lang)}catch{}},[lang]);
 useEffect(()=>{if(page==='profile'&&profileTarget){document.getElementById(profileTarget)?.scrollIntoView({behavior:'smooth'});setProfileTarget('')}},[page,profileTarget]);
 useEffect(()=>onAuthStateChanged(auth,setUser),[]);
 useEffect(()=>{
  setRows([]);setError('');setLoading(false);let q;
  if(page==='jobs')q=query(collection(db,'jobPosts'),where('status','==','published'),limit(rowLimit));
  if(page==='services')q=query(collection(db,'technicianProfiles'),where('status','==','approved'),limit(rowLimit));
  if(page==='profile'&&user)q=query(collection(db,'jobApplications'),where('candidateId','==',user.uid),limit(rowLimit));
  if(!q)return;setLoading(true);return onSnapshot(q,snapshot=>{setRows(snapshot.docs.map(d=>({id:d.id,...d.data()})));setLoading(false)},()=>{setLoading(false);setError(s('Маълумот бор нашуд. Боз санҷед.','Не удалось загрузить данные. Попробуйте снова.','Ma’lumot yuklanmadi. Qayta urinib ko‘ring.'))});
 },[page,user,lang,retry,rowLimit]);
 useEffect(()=>{function close(e:KeyboardEvent){if(e.key==='Escape'){setModal(null);setSelected(null)}}addEventListener('keydown',close);return()=>removeEventListener('keydown',close)},[]);
 async function run(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');setNotice('');try{await fn()}catch{setError(t.error)}finally{setBusy(false)}}
 function requireUser(m:'job'|'driver'|'technician'){setModal(user?m:'auth')}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{
  if(modal==='auth'){const email=String(f.get('email')),password=String(f.get('password'));if(register){const c=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(c.user,{displayName:String(f.get('name')).trim()});setUser(c.user)}else await signInWithEmailAndPassword(auth,email,password)}
  if(modal==='job')await action({kind:'createJob',title:f.get('title'),company:f.get('company'),description:f.get('description'),city:'Dushanbe'});
  if(modal==='driver'||modal==='technician')await action({kind:'providerApplication',role:modal,name:f.get('name'),vehicle:f.get('vehicle'),plate:f.get('plate'),skills:f.get('skills')});
  if(modal==='info'&&user){await updateProfile(user,{displayName:String(f.get('name')).trim()});setUser(user)}
  if(modal==='job'||modal==='driver'||modal==='technician')setNotice(s('Ариза барои санҷиш фиристода шуд.','Заявка отправлена на проверку.','Ariza tekshirish uchun yuborildi.'));
  setModal(null)
 })}
 const jobCats=[['all',s('Ҳама','Все','Barchasi')],['driver',s('Ронанда','Водитель','Haydovchi')],['technician',t.services],['office',s('Идора','Офис','Ofis')],['trade',s('Савдо','Торговля','Savdo')],['food',s('Ғизо','Питание','Ovqat')]];
 const serviceCats=[['all',s('Ҳама','Все','Barchasi')],['repair',s('Таъмир','Ремонт','Ta’mirlash')],['finishing',s('Ороиш','Отделка','Pardozlash')],['electrical',s('Барқ','Электрика','Elektr')],['plumbing',s('Қубур','Сантехника','Santexnika')],['climate',s('Иқлим','Климат','Iqlim')]];
 const visible=rows.filter(r=>(category==='all'||r.category===category)&&[r.title,r.name,r.company,r.description,r.city].filter(Boolean).join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>sort==='name'?(a.title||a.name||'').localeCompare(b.title||b.name||''):sort==='salary'?(b.salaryMin||0)-(a.salaryMin||0):(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));
 const modalTitles:Record<Exclude<Modal,null>,string>={auth:register?t.register:t.login,job:t.publish,driver:t.driver,technician:s('Аризаи усто','Заявка мастера','Ustalik arizasi'),info:s('Маълумоти ман','Мои данные','Ma’lumotlarim'),payment:t.payment,addresses:s('Суроғаҳои ман','Мои адреса','Manzillarim'),language:s('Забон','Язык','Til'),notifications:s('Огоҳиномаҳо','Уведомления','Bildirishnomalar'),security:s('Амният','Безопасность','Xavfsizlik'),help:s('Ёрӣ','Помощь','Yordam'),about:s('Дар бораи барнома','О приложении','Ilova haqida'),balance:s('Тавозун','Баланс','Balans'),promos:s('Промокодҳо','Промокоды','Promokodlar'),contact:s('Бо мо тамос гиред','Связаться с нами','Biz bilan bog‘lanish')};
 const profileGroups=[{title:s('Маълумоти шахсӣ','Личные данные','Shaxsiy ma’lumotlar'),items:[['info','profile',modalTitles.info,s('Ном ва email','Имя и email','Ism va email')],['payment','card',t.payment,s('Нақд ё интиқоли мустақим','Наличные или прямой перевод','Naqd yoki bevosita o‘tkazma')],['addresses','pin',modalTitles.addresses,s('Хона, кор ва дигар ҷойҳо','Дом, работа и другие места','Uy, ish va boshqa joylar')]]},{title:s('Танзимот','Настройки','Sozlamalar'),items:[['language','language',modalTitles.language,{tg:'Тоҷикӣ',ru:'Русский',uz:'O‘zbekcha'}[lang]],['notifications','bell',modalTitles.notifications,s('Фармоишҳо ва навигариҳо','Заказы и новости','Buyurtmalar va yangiliklar')],['security','shield',modalTitles.security,s('Воридшавӣ ва махфият','Вход и конфиденциальность','Kirish va maxfiylik')]]},{title:s('Дастгирӣ','Поддержка','Qo‘llab-quvvatlash'),items:[['help','support',modalTitles.help,s('Саволҳо ва ҷавобҳо','Вопросы и ответы','Savollar va javoblar')],['contact','chat',modalTitles.contact,s('Дастгирӣ','Поддержка','Yordam')],['about','info',modalTitles.about,'Cavi Go · Capline Group']] }];
 const languageControl=<select aria-label={modalTitles.language} value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="tg">Тоҷикӣ</option><option value="ru">Русский</option><option value="uz">O‘zbekcha</option></select>;
 return <>
  <header className="app-header"><div className="header-brand">{page!=='home'&&<button className="icon-button" aria-label={t.home} onClick={()=>go('home')}><Icon name="back"/></button>}<button className="logo" onClick={()=>go('home')}>Cavi <span>Go</span></button></div><div className="header-actions">{page==='profile'?<button className="settings-button" onClick={()=>document.getElementById('profile-settings')?.scrollIntoView({behavior:'smooth'})}><Icon name="settings"/>{s('Танзимот','Настройки','Sozlamalar')}</button>:<button className="profile-button" aria-label={t.profile} onClick={()=>go('profile')}><Icon name="profile"/></button>}</div></header>
  <main className={page==='taxi'?'taxi-main':`app-main page-${page}`}>
   {error&&page!=='taxi'&&<div role="alert" className="error">{error}{(page==='jobs'||page==='services'||page==='profile')&&<button className="light" onClick={()=>setRetry(x=>x+1)}>{s('Боз санҷед','Повторить','Qayta urinish')}</button>}</div>}{notice&&<div className="success" role="status">{notice}</div>}
   {page==='home'&&<>
    <section className="orders-preview"><div className="section-heading"><h2>{s('Фармоишҳои фаъол','Активные заказы','Faol buyurtmalar')}</h2><button className="text-button" aria-label={s('Ҳамаи фармоишҳо','Все заказы','Barcha buyurtmalar')} onClick={()=>{go('profile');setProfileTarget('my-orders')}}>{s('Ҳама','Все','Barchasi')} <Icon name="arrow"/></button></div><div className="no-orders"><span className="icon-disc"><Icon name="clock"/></span><div><b>{s('Ҳоло фармоиши фаъол нест','Пока нет активных заказов','Hozir faol buyurtma yo‘q')}</b><p>{s('Хизматҳои Cavi Go-ро дар поён интихоб кунед.','Выберите сервис Cavi Go ниже.','Quyidan Cavi Go xizmatini tanlang.')}</p></div></div></section>
    <div className="catalog-heading"><h2>{s('Хизматҳо','Сервисы','Xizmatlar')}</h2><span><Icon name="pin"/>{t.city}</span></div><div className="service-grid">{(['taxi','services','jobs','delivery','fuel'] as Page[]).map(p=><button className={'service-tile service-'+p} key={p} aria-label={pageName(p)} onClick={()=>go(p)}><span className="tile-art"><ServiceArt kind={p}/></span><span className="tile-label"><strong>{tileName(p)}</strong><span className="tile-arrow"><Icon name="arrow"/></span></span></button>)}{[1,2,3].map(n=><div key={n} className="service-tile coming-tile"><span className="coming-plus"><Icon name="plus"/></span><strong>{s('Ба зудӣ','Скоро','Tez kunda')}</strong></div>)}</div>
    <section className="launch-card"><span className="launch-pin"><Icon name="pin"/></span><div><b>{t.city} · Cavi Go</b><p>{t.pending}</p></div><button className="launch-more" aria-label={modalTitles.about} onClick={()=>setModal('about')}><Icon name="chevron"/></button></section>
    <section className="join-card"><div><p className="eyebrow">CAVI GO PARTNERS</p><h2>{s('Бо Cavi Go ҳамкорӣ кунед','Присоединяйтесь к Cavi Go','Cavi Go’ga qo‘shiling')}</h2><p>{s('Барои ронандаҳо, устоҳо ва корфармоён.','Для водителей, мастеров и работодателей.','Haydovchilar, ustalar va ish beruvchilar uchun.')}</p><div className="join-actions"><button onClick={()=>requireUser('driver')}><Icon name="taxi"/>{t.taxi}<Icon name="arrow"/></button><button onClick={()=>requireUser('technician')}><Icon name="services"/>{t.services}<Icon name="arrow"/></button><button onClick={()=>requireUser('job')}><Icon name="jobs"/>{t.jobs}<Icon name="arrow"/></button></div></div><span className="partner-mark" aria-hidden="true">Go<span>↗</span></span></section>
    <section className="benefits"><h2>{s('Чаро Cavi Go?','Почему Cavi Go?','Nega Cavi Go?')}</h2><div><article><Icon name="shield"/><b>{s('Профили шахсӣ','Личный профиль','Shaxsiy profil')}</b><p>{s('Аризаҳо дар ҳисоби шумо','Заявки в вашем аккаунте','Arizalar hisobingizda')}</p></article><article><Icon name="clock"/><b>{s('Қулай','Удобно','Qulay')}</b><p>{s('Хизматҳо дар як ҷо','Сервисы в одном месте','Xizmatlar bir joyda')}</p></article><article><Icon name="pin"/><b>{s('Харитаи маҳаллӣ','Местная карта','Mahalliy xarita')}</b><p>Cavi Maps</p></article><article><Icon name="grid"/><b>{s('Барои ҳама','Для всех','Hamma uchun')}</b><p>{s('Кор, усто ва такси','Работа, мастера и такси','Ish, ustalar va taksi')}</p></article></div></section>
   </>}
   {(page==='jobs'||page==='services')&&<>
    <div className="page-heading"><div><h1>{pageName(page)}</h1><p>{page==='jobs'?s('Дар Тоҷикистон кори худро ёбед.','Найдите работу в Таджикистане.','Tojikistonda ish toping.'):s('Барои кори худ усто интихоб кунед.','Выберите мастера для вашей задачи.','Ishingiz uchun usta tanlang.')}</p></div><button className="round-add" aria-label={page==='jobs'?t.publish:modalTitles.technician} onClick={()=>requireUser(page==='jobs'?'job':'technician')}>＋</button></div>
    <div className="directory-tools"><label className="search-box"><Icon name="search"/><input aria-label={s('Ҷустуҷӯ','Поиск','Qidirish')} placeholder={page==='jobs'?s('Вазифа ё ташкилот','Должность или компания','Lavozim yoki tashkilot'):s('Ном, хизмат ё суроға','Имя, услуга или адрес','Ism, xizmat yoki manzil')} value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="chips">{(page==='jobs'?jobCats:serviceCats).map(([key,name])=><button key={key} aria-pressed={category===key} onClick={()=>setCategory(key)}><Icon name={({all:'grid',driver:'taxi',technician:'services',office:'jobs',trade:'shop',food:'food',repair:'services',finishing:'paint',electrical:'plug',plumbing:'faucet',climate:'climate'} as Record<string,string>)[key]}/>{name}</button>)}</div><div className="directory-controls"><span><Icon name="filter"/>{category==='all'?s('Ҳамаи гурӯҳҳо','Все категории','Barcha toifalar'):(page==='jobs'?jobCats:serviceCats).find(x=>x[0]===category)?.[1]}</span><select aria-label={s('Тартиб','Сортировка','Saralash')} value={sort} onChange={e=>setSort(e.target.value)}><option value="new">{s('Навтарин','Сначала новые','Avval yangilari')}</option><option value="name">{s('Аз рӯи ном','По названию','Nom bo‘yicha')}</option>{page==='jobs'&&<option value="salary">{s('Аз рӯи маош','По зарплате','Maosh bo‘yicha')}</option>}</select></div></div>
    {loading?<section className="empty" role="status"><span className="loading-dot"/>{s('Бор шуда истодааст…','Загрузка…','Yuklanmoqda…')}</section>:visible.length?<div className="directory-list">{visible.map(r=><button className="directory-card" key={r.id} onClick={()=>setSelected(r)}><span className="listing-art"><Icon name={page}/></span><span className="listing-body"><strong>{r.title||r.name}</strong>{r.company&&<small>{r.company}</small>}<span className="listing-meta"><Icon name="pin"/>{r.city||t.city}</span>{r.salaryMin!==undefined&&<b className="salary">{r.salaryMin.toLocaleString()}{r.salaryMax?`–${r.salaryMax.toLocaleString()}`:''} TJS</b>}{r.description&&<small className="clamp">{r.description}</small>}</span><Icon name="arrow"/></button>)}</div>:<section className="empty"><span className="empty-icon"><Icon name={search?'search':page}/></span><h2>{search||category!=='all'?s('Натиҷа нест','Ничего не найдено','Natija topilmadi'):t.empty}</h2><p>{search||category!=='all'?s('Ҷустуҷӯ ё гурӯҳро тағйир диҳед.','Измените поиск или категорию.','Qidiruv yoki toifani o‘zgartiring.'):s('Маълумоти санҷидашуда баъд аз илова шудан пайдо мешавад.','Проверенные объявления появятся после добавления.','Tasdiqlangan e’lonlar qo‘shilganda ko‘rinadi.')}</p></section>}
    {rows.length===rowLimit&&rowLimit<100&&<button className="load-more light" onClick={()=>setRowLimit(n=>n+20)}>{s('Бештар нишон диҳед','Показать ещё','Yana ko‘rsatish')}</button>}
   </>}
   {page==='taxi'&&<Suspense fallback={<section className="empty">{t.map}…</section>}><Taxi lang={lang}/></Suspense>}
   {page==='fuel'&&<Suspense fallback={<section className="empty">{t.map}…</section>}><Fuel lang={lang}/></Suspense>}
   {page==='delivery'&&<><div className="page-heading"><div><h1><Icon name="delivery"/>{pageName('delivery')}</h1><p>{s('Ғизо, маҳсулот ва молҳо дар як ҷо.','Еда, продукты и товары в одном месте.','Ovqat, mahsulotlar va tovarlar bir joyda.')}</p></div><span className="city-pill"><Icon name="pin"/>{t.city}</span></div><label className="search-box"><Icon name="search"/><input aria-label={s('Ҷустуҷӯи мағоза','Поиск магазинов','Do‘kon qidirish')} placeholder={s('Мағоза, ғизо ё маҳсулот','Магазин, блюдо или товар','Do‘kon, taom yoki mahsulot')} value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="delivery-categories">{[['all','grid',s('Ҳама','Все','Barchasi')],['food','food',s('Ғизо','Еда','Ovqat')],['grocery','basket',s('Маҳсулот','Продукты','Mahsulotlar')],['pharmacy','medical',s('Дорухона','Аптека','Dorixona')],['flowers','flower',s('Гулҳо','Цветы','Gullar')],['electronics','headphones',s('Электроника','Электроника','Elektronika')]].map(([key,icon,name])=><button key={key} aria-pressed={deliveryCategory===key} onClick={()=>setDeliveryCategory(key)}><Icon name={icon}/>{name}</button>)}</div><section className="empty"><span className="empty-icon"><Icon name="delivery"/></span><h2>{s('Расонидан ба зудӣ','Доставка скоро','Yetkazib berish tez kunda')}</h2><p>{s('Ҳоло шарикони расонидан пайваст нашудаанд.','Партнёры доставки пока не подключены.','Yetkazib berish hamkorlari hali ulanmagan.')}</p></section></>}
   {page==='profile'&&<>
    <button className="profile-card" onClick={()=>setModal(user?'info':'auth')}><span className="avatar"><Icon name="profile"/></span><span><strong>{user?.displayName||s('Хуш омадед','Добро пожаловать','Xush kelibsiz')}</strong><small>{user?.email||t.signin}</small></span><Icon name="arrow"/></button>
    <div className="profile-shortcuts"><button onClick={()=>setModal('balance')}><Icon name="wallet"/><span><small>{modalTitles.balance}</small><b>{s('Ба зудӣ','Скоро','Tez kunda')}</b></span><Icon name="chevron"/></button><button onClick={()=>setModal('promos')}><Icon name="ticket"/><span><small>{modalTitles.promos}</small><b>{s('Ба зудӣ','Скоро','Tez kunda')}</b></span><Icon name="chevron"/></button><button onClick={()=>document.getElementById('my-orders')?.scrollIntoView({behavior:'smooth'})}><Icon name="clock"/><span><small>{s('Таърих','История','Tarix')}</small><b>{t.orders}</b></span><Icon name="chevron"/></button></div>
    <section className="my-orders" id="my-orders"><div className="section-heading"><h2>{t.orders}</h2><Icon name="clock"/></div>{user?loading?<p>{s('Бор шуда истодааст…','Загрузка…','Yuklanmoqda…')}</p>:rows.length?rows.map(r=><article key={r.id}><b>{r.title||s('Ариза ба кор','Отклик на вакансию','Ishga ariza')}</b><p>{t.status}: {r.status}</p>{r.jobId&&<small>{r.jobId}</small>}</article>):<p className="muted">{t.empty}</p>:<button className="light" onClick={()=>setModal('auth')}>{t.login}</button>}</section>
    {profileGroups.map((g,i)=><section className="profile-group" id={i===1?'profile-settings':undefined} key={g.title}><h2>{g.title}</h2><div>{g.items.map(([m,icon,title,subtitle])=><button className="profile-row" key={m} onClick={()=>setModal(m as Modal)}><Icon name={icon}/><span><strong>{title}</strong><small>{subtitle}</small></span><Icon name="arrow"/></button>)}</div></section>)}
    <button className="partner-button light" onClick={()=>requireUser('driver')}><Icon name="taxi"/>{t.driver}<Icon name="arrow"/></button>{user&&<button className="logout-button" disabled={busy} onClick={()=>run(async()=>{await signOut(auth);setRows([])})}><Icon name="logout"/>{t.logout}</button>}
   </>}
  </main>
  {(modal||selected)&&<div className="overlay" onClick={()=>{setModal(null);setSelected(null)}}><section className="dialog" role="dialog" aria-modal="true" aria-label={selected?(selected.title||selected.name):modal?modalTitles[modal]:''} onClick={e=>e.stopPropagation()}><button className="close light" onClick={()=>{setModal(null);setSelected(null)}} aria-label={s('Пӯшидан','Закрыть','Yopish')}>×</button><h2>{selected?(selected.title||selected.name):modal?modalTitles[modal]:''}</h2>
   {error&&<div className="error" role="alert">{error}</div>}
   {selected?<><p className="muted">{selected.company} · {selected.city||t.city}</p>{selected.description&&<p className="detail-description">{selected.description}</p>}{selected.salaryMin!==undefined&&<p><b>{selected.salaryMin}{selected.salaryMax?`–${selected.salaryMax}`:''} TJS</b></p>}{selected.experience&&<p>{selected.experience}</p>}{selected.employmentType&&<p>{selected.employmentType}</p>}{page==='jobs'&&<button disabled={busy} onClick={()=>user?run(async()=>{await action({kind:'applyJob',jobId:selected.id});setSelected(null);setNotice(s('Ариза фиристода шуд.','Отклик отправлен.','Ariza yuborildi.'))}):(setSelected(null),setModal('auth'))}>{t.apply}</button>}</>:
   (modal==='auth'||modal==='job'||modal==='driver'||modal==='technician'||(modal==='info'&&user))?<form onSubmit={submit}>
    {modal==='auth'?<>{register&&<label>{t.name}<input name="name" autoComplete="name" required maxLength={80}/></label>}<label>{t.email}<input name="email" type="email" autoComplete="email" required/></label><label>{t.password}<input name="password" type="password" minLength={8} autoComplete={register?'new-password':'current-password'} required/></label></>:modal==='job'?<><label>{t.titleField}<input name="title" required maxLength={120}/></label><label>{t.company}<input name="company" required maxLength={120}/></label><label>{t.description}<textarea name="description" required maxLength={4000}/></label></>:<><label>{t.name}<input name="name" defaultValue={user?.displayName||''} required maxLength={80}/></label>{modal==='info'?<p>{user?.email}</p>:modal==='driver'?<><label>{s('Автомобил','Автомобиль','Avtomobil')}<input name="vehicle" required maxLength={80}/></label><label>{s('Рақами автомобил','Номер автомобиля','Avtomobil raqami')}<input name="plate" required maxLength={20}/></label></>:<label>{s('Ихтисос','Специализация','Mutaxassislik')}<input name="skills" required maxLength={120}/></label>}</>}
    <button disabled={busy}>{busy?'…':modal==='auth'?(register?t.register:t.login):t.save}</button>{modal==='auth'&&<button type="button" className="light" onClick={()=>setRegister(!register)}>{register?t.login:t.register}</button>}
   </form>:
   modal==='language'?languageControl:
   modal==='payment'?<><div className="setting-option"><Icon name="card"/>{t.cash}</div><div className="setting-option"><Icon name="card"/>{t.transfer}</div><p>{t.notice}</p></>:
   modal==='addresses'?<><p>{s('Суроғаи захирашуда нест. Барои сафар нуқтаро дар харита интихоб кунед.','Сохранённых адресов нет. Выберите точку на карте для поездки.','Saqlangan manzil yo‘q. Safar uchun xaritadan nuqta tanlang.')}</p><button onClick={()=>go('taxi')}>{t.map}</button></>:
   modal==='notifications'?<p>{s('Огоҳиномаҳои фармоиш баъд аз оғози хизмат фаъол мешаванд.','Уведомления о заказах появятся после запуска сервиса.','Buyurtma bildirishnomalari xizmat ishga tushganda faollashadi.')}</p>:
   modal==='security'?<><p>{s('Аризаҳои шахсӣ тавассути ҳисоби шумо кушода мешаванд.','Личные заявки открываются через ваш аккаунт.','Shaxsiy arizalar hisobingiz orqali ochiladi.')}</p>{user?.email?<button disabled={busy} onClick={()=>run(async()=>{await sendPasswordResetEmail(auth,user.email!);setModal(null);setNotice(s('Ба email пайванди тағйири рамз фиристода шуд.','Ссылка для сброса пароля отправлена на email.','Parolni tiklash havolasi emailga yuborildi.'))})}>{s('Тағйири рамз','Сбросить пароль','Parolni tiklash')}</button>:<button onClick={()=>setModal('auth')}>{t.login}</button>}</>:
   (modal==='help'||modal==='contact')?<><p>{t.pending}</p><p>{s('Барои саволҳо ба Capline Group нависед.','По вопросам пишите в Capline Group.','Savollar uchun Capline Group’ga yozing.')}</p><a className="support-link" href="mailto:caplinegroup.tj@gmail.com">caplinegroup.tj@gmail.com</a></>:
   (modal==='balance'||modal==='promos')?<p>{s('Ин имконият ҳоло фаъол нест.','Эта возможность пока не подключена.','Bu imkoniyat hali ulanmagan.')}</p>:
   modal==='about'?<><b>Cavi Go · {brand.company}</b><p>{t.subtitle}</p><p>Cavi Maps · © OpenStreetMap contributors</p><p className="muted">0.2.0</p></>:
   <><p>{t.signin}</p><button onClick={()=>setModal('auth')}>{t.login}</button></>}
  </section></div>}
 </>
}
createRoot(document.getElementById('root')!).render(<App/>);
