import {useEffect,useRef,useState} from 'react';
import {Marker} from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import {createAtlasGL,baseLabels,AtlasGL} from './map-engine/atlas-gl';
import {text,Lang} from './i18n';
type Place={id:string;lat:number;lon:number;tags:Record<string,string>};
type Point={lat:number;lon:number;name:string;detail?:string};
const messages={tg:{search:'Ҷой ё суроғаро ҷустуҷӯ кунед',map:'Дар харита интихоб кунед',select:'Интихоб кардан',back:'Бозгашт',hint:'Ҷойро дар харита пахш кунед',empty:'Ҷой ёфт нашуд',loading:'Харита бор шуда истодааст…'},ru:{search:'Место или адрес',map:'Выбрать на карте',select:'Выбрать',back:'Назад',hint:'Нажмите нужное место на карте',empty:'Место не найдено',loading:'Загружаем карту…'},uz:{search:'Joy yoki manzilni qidiring',map:'Xaritadan tanlash',select:'Tanlash',back:'Orqaga',hint:'Xaritada kerakli joyni bosing',empty:'Joy topilmadi',loading:'Xarita yuklanmoqda…'}};
const pointName=(p:Place)=>p.tags.name||p.tags['name:ru']||p.tags['addr:street']||'📍';
const pointDetail=(p:Place)=>[p.tags['addr:city'],p.tags['addr:street'],p.tags['addr:housenumber']].filter(Boolean).join(', ');
export function Taxi({lang}:{lang:Lang}){
 const t=text[lang],m=messages[lang],node=useRef<HTMLDivElement>(null),engine=useRef<AtlasGL|null>(null),active=useRef<'from'|'to'>('to');
 const[from,setFrom]=useState<Point|null>(null),[to,setTo]=useState<Point|null>(null),[editing,setEditing]=useState<'from'|'to'|null>(null),[q,setQ]=useState(''),[places,setPlaces]=useState<Place[]>([]),[selected,setSelected]=useState<Point|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false),[pay,setPay]=useState('cash');
 useEffect(()=>{if(!node.current)return;let disposed=false;const a=createAtlasGL(node.current,()=>{if(!disposed)setError(t.error)});engine.current=a;a.map.jumpTo({center:[68.7869,38.5737],zoom:14});
 a.ready.then(()=>{if(!disposed)setReady(true)}).catch(()=>{if(!disposed)setError(t.error)});
 baseLabels().then(l=>{if(!disposed)a.setLabels(l)}).catch(()=>{});
 const controller=new AbortController();fetch('https://sultonmusic.github.io/cavi-maps/places.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(p=>{if(!disposed)setPlaces(p.filter((x:Place)=>Number.isFinite(x.lat)&&Number.isFinite(x.lon)&&x.tags))}).catch(e=>{if(!disposed&&e.name!=='AbortError')setError(t.error)});
 const pick=(e:{lngLat:{lat:number;lng:number}})=>{const{lat,lng}=e.lngLat;if(lat<35.5||lat>42||lng<66||lng>76.5)return;setSelected({lat,lon:lng,name:lang==='uz'?'Xaritadagi joy':lang==='ru'?'Точка на карте':'Ҷой дар харита',detail:`${lat.toFixed(5)}, ${lng.toFixed(5)}`})};a.map.on('click',pick);
 return()=>{disposed=true;controller.abort();a.destroy();engine.current=null};},[]);
 useEffect(()=>{const a=engine.current;if(!a||!ready)return;const pins:Marker[]=[];for(const[p,label]of [[from,'A'],[to,'B']] as const){if(!p)continue;const el=document.createElement('div');el.className='taxi-pin';el.textContent=label;pins.push(new Marker({element:el}).setLngLat([p.lon,p.lat]).addTo(a.map))}return()=>pins.forEach(p=>p.remove())},[from,to,ready]);
 function open(kind:'from'|'to'){active.current=kind;setEditing(kind);setQ('');setSelected(null)}
 function choose(p:Point){active.current==='from'?setFrom(p):setTo(p);setSelected(null);setEditing(null);engine.current?.map.easeTo({center:[p.lon,p.lat],zoom:16,offset:[0,-100]})}
 function locate(){setError('');if(!navigator.geolocation){setError(t.error);return}navigator.geolocation.getCurrentPosition(p=>{const{latitude:lat,longitude:lon}=p.coords;if(lat<35.5||lat>42||lon<66||lon>76.5){setError(t.error);return}const at={lat,lon,name:t.locate};setFrom(at);engine.current?.map.easeTo({center:[lon,lat],zoom:16})},()=>setError(t.error),{timeout:12000,maximumAge:30000,enableHighAccuracy:true})}
 const matches=q.trim()?places.filter(p=>Object.values(p.tags).join(' ').toLocaleLowerCase().includes(q.trim().toLocaleLowerCase())).sort((a,b)=>(a.lat-38.5737)**2+(a.lon-68.7869)**2-((b.lat-38.5737)**2+(b.lon-68.7869)**2)).slice(0,30):places.filter(p=>Math.abs(p.lat-38.5737)<.07&&Math.abs(p.lon-68.7869)<.07&&p.tags.name).slice(0,12);
 return <section className="taxi-scene" aria-label={t.taxi}><div ref={node} className="taxi-map"/>{!ready&&<div className="map-loading">{m.loading}</div>}<div className="taxi-badge">Cavi Maps · {t.city}</div><button className="gps-button" aria-label={t.locate} onClick={locate}>⌖</button>
 {error&&<div className="taxi-error" role="alert">{error}</div>}
 <section className="taxi-sheet"><div className="sheet-handle"/><div className="taxi-sheet-heading"><strong>{t.taxi}</strong><span>Cavi Go</span></div><button className="address-row" onClick={()=>open('from')}><i className="from-dot"/><div><small>{t.from}</small><strong>{from?.name||t.locate}</strong>{from?.detail&&<small>{from.detail}</small>}</div><span>›</span></button><button className="address-row" onClick={()=>open('to')}><i className="to-dot"/><div><small>{t.to}</small><strong>{to?.name||m.search}</strong>{to?.detail&&<small>{to.detail}</small>}</div><span>›</span></button><div className="payment-row"><span>{t.payment}</span><select aria-label={t.payment} value={pay} onChange={e=>setPay(e.target.value)}><option value="cash">{t.cash}</option><option value="direct_transfer">{t.transfer}</option></select></div><button className="order-button" disabled>{t.request}</button><p className="launch-note">{t.pending}</p></section>
 {editing&&<section className="address-search" role="dialog" aria-modal="true" aria-label={editing==='from'?t.from:t.to}><div className="search-heading"><button className="light" aria-label={m.back} onClick={()=>setEditing(null)}>←</button><h2>{editing==='from'?t.from:t.to}</h2></div><input autoFocus aria-label={m.search} placeholder={m.search} value={q} onChange={e=>setQ(e.target.value)}/><button className="map-pick" onClick={()=>{setEditing(null);setSelected(null)}}>⌖ {m.map}</button><div className="address-results">{matches.map(p=><button key={p.id} onClick={()=>setSelected({lat:p.lat,lon:p.lon,name:pointName(p),detail:pointDetail(p)})}><span>📍</span><div><strong>{pointName(p)}</strong><small>{pointDetail(p)}</small></div><span>›</span></button>)}{q&&!matches.length&&<p>{m.empty}</p>}</div></section>}
 {selected&&<section className="place-detail" role="dialog" aria-modal="true" aria-label={selected.name}><button className="close light" aria-label={m.back} onClick={()=>setSelected(null)}>×</button><small>{active.current==='from'?t.from:t.to}</small><h2>{selected.name}</h2><p>{selected.detail}</p><button onClick={()=>choose(selected)}>{m.select}</button></section>}
 <span className="map-attribution">© OpenStreetMap contributors · Cavi Maps</span></section>
}
