import {useEffect,useRef,useState} from 'react';
import {Marker,type MapMouseEvent} from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import {createAtlasGL,baseLabels,AtlasGL} from './map-engine/atlas-gl';
import {text,Lang} from './i18n';
import {loadPlaces,type Place} from './places';
import {Icon,Car,say} from './ui';
type Point={lat:number;lon:number;name:string;detail?:string};
const messages={tg:{search:'Ҷой ё суроғаро ҷустуҷӯ кунед',map:'Дар харита интихоб кунед',select:'Интихоб кардан',back:'Бозгашт',hint:'Ҷойро дар харита пахш кунед',empty:'Ҷой ёфт нашуд',loading:'Харита бор шуда истодааст…'},ru:{search:'Место или адрес',map:'Выбрать на карте',select:'Выбрать',back:'Назад',hint:'Нажмите нужное место на карте',empty:'Место не найдено',loading:'Загружаем карту…'},uz:{search:'Joy yoki manzilni qidiring',map:'Xaritadan tanlash',select:'Tanlash',back:'Orqaga',hint:'Xaritada kerakli joyni bosing',empty:'Joy topilmadi',loading:'Xarita yuklanmoqda…'}};
const pointName=(p:Place)=>p.tags.name||p.tags['name:ru']||p.tags['addr:street']||'📍';
const pointDetail=(p:Place)=>[p.tags['addr:city'],p.tags['addr:street'],p.tags['addr:housenumber']].filter(Boolean).join(', ');
export function Taxi({lang}:{lang:Lang}){
 const t=text[lang],m=messages[lang],node=useRef<HTMLDivElement>(null),engine=useRef<AtlasGL|null>(null),active=useRef<'from'|'to'>('to'),placesRef=useRef<Place[]>([]),langRef=useRef(lang);langRef.current=lang;
 const[from,setFrom]=useState<Point|null>(null),[to,setTo]=useState<Point|null>(null),[editing,setEditing]=useState<'from'|'to'|null>(null),[q,setQ]=useState(''),[places,setPlaces]=useState<Place[]>([]),[selected,setSelected]=useState<Point|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false),[pay,setPay]=useState('cash'),[mode,setMode]=useState('taxi'),[vehicle,setVehicle]=useState('economy');
 const s=(tg:string,ru:string,uz:string)=>say(lang,tg,ru,uz);
 useEffect(()=>{if(!node.current)return;let disposed=false;let a:AtlasGL;try{a=createAtlasGL(node.current,()=>{if(!disposed)setError(t.error)})}catch{setError(t.error);return}engine.current=a;a.map.jumpTo({center:[68.7869,38.5737],zoom:14});
 a.ready.then(()=>{if(!disposed)setReady(true)}).catch(()=>{if(!disposed)setError(t.error)});
 baseLabels().then(l=>{if(!disposed)a.setLabels(l)}).catch(()=>{});
 loadPlaces().then(p=>{if(!disposed){placesRef.current=p;setPlaces(p)}}).catch(()=>{if(!disposed)setError(t.error)});
 const pick=(e:MapMouseEvent)=>{const hit=a.pick(e);if(hit.kind==='point'){const p=placesRef.current.find(p=>p.id===hit.id);if(p){setSelected({lat:p.lat,lon:p.lon,name:pointName(p),detail:[pointDetail(p),p.tags.opening_hours].filter(Boolean).join(' · ')});return}}if(hit.kind==='label'){setSelected({lat:hit.label.lat,lon:hit.label.lon,name:hit.label.name});return}const{lat,lng}=e.lngLat;if(lat<35.5||lat>42||lng<66||lng>76.5)return;setSelected({lat,lon:lng,name:say(langRef.current,'Ҷой дар харита','Точка на карте','Xaritadagi joy'),detail:`${lat.toFixed(5)}, ${lng.toFixed(5)}`})};a.map.on('click',pick);
 return()=>{disposed=true;a.destroy();engine.current=null};},[]);
 useEffect(()=>{if(ready&&engine.current)engine.current.setPoints(places.map(p=>({id:p.id,lat:p.lat,lon:p.lon,name:pointName(p),category:p.tags.amenity||p.tags.shop||'place',rank:2})))},[ready,places]);
 useEffect(()=>{const a=engine.current;if(!a||!ready)return;const pins:Marker[]=[];for(const[p,label]of [[from,'A'],[to,'B']] as const){if(!p)continue;const el=document.createElement('div');el.className='taxi-pin';el.textContent=label;pins.push(new Marker({element:el}).setLngLat([p.lon,p.lat]).addTo(a.map))}return()=>pins.forEach(p=>p.remove())},[from,to,ready]);
 function open(kind:'from'|'to'){active.current=kind;setEditing(kind);setQ('');setSelected(null)}
 function choose(p:Point){active.current==='from'?setFrom(p):setTo(p);setSelected(null);setEditing(null);engine.current?.map.easeTo({center:[p.lon,p.lat],zoom:16,offset:[0,-100]})}
 function locate(){setError('');if(!navigator.geolocation){setError(t.error);return}navigator.geolocation.getCurrentPosition(p=>{const{latitude:lat,longitude:lon}=p.coords;if(lat<35.5||lat>42||lon<66||lon>76.5){setError(t.error);return}const at={lat,lon,name:t.locate};setFrom(at);engine.current?.map.easeTo({center:[lon,lat],zoom:16})},()=>setError(t.error),{timeout:12000,maximumAge:30000,enableHighAccuracy:true})}
 const matches=q.trim()?places.filter(p=>Object.values(p.tags).join(' ').toLocaleLowerCase().includes(q.trim().toLocaleLowerCase())).sort((a,b)=>(a.lat-38.5737)**2+(a.lon-68.7869)**2-((b.lat-38.5737)**2+(b.lon-68.7869)**2)).slice(0,30):places.filter(p=>Math.abs(p.lat-38.5737)<.07&&Math.abs(p.lon-68.7869)<.07&&p.tags.name).slice(0,12);
 return <section className="taxi-scene" aria-label={t.taxi}><div ref={node} className="taxi-map"/>{!ready&&<div className="map-loading">{m.loading}</div>}<button className="gps-button" aria-label={t.locate} onClick={locate}>⌖</button>
 {error&&<div className="taxi-error" role="alert">{error}</div>}
 <section className="taxi-sheet"><div className="sheet-handle"/><div className="ride-tabs">{[['taxi',t.taxi],['intercity',s('Байнишаҳрӣ','Межгород','Shaharlararo')],['delivery',s('Расонидан','Доставка','Yetkazish')]].map(([key,name])=><button key={key} aria-pressed={mode===key} onClick={()=>setMode(key)}><Icon name={key==='delivery'?'delivery':'taxi'}/>{name}</button>)}</div><button className="address-row" onClick={()=>open('from')}><i className="from-dot"/><div><small>{t.from}</small><strong>{from?.name||m.search}</strong>{from?.detail&&<small>{from.detail}</small>}</div><span>›</span></button><button className="address-row" onClick={()=>open('to')}><i className="to-dot"/><div><small>{t.to}</small><strong>{to?.name||m.search}</strong>{to?.detail&&<small>{to.detail}</small>}</div><span>›</span></button><div className="quick-addresses"><button onClick={()=>open('to')}><Icon name="home"/>{s('Хона','Дом','Uy')}</button><button onClick={()=>open('to')}><Icon name="jobs"/>{s('Кор','Работа','Ish')}</button><button onClick={()=>open('to')}><Icon name="star"/>{s('Дӯстдошта','Избранное','Sevimlilar')}</button><button onClick={()=>open('to')}><Icon name="plus"/>{s('Дигар','Другое','Boshqa')}</button></div><div className="vehicle-grid">{[['economy',s('Иқтисодӣ','Эконом','Ekonom')],['comfort',s('Бароҳат','Комфорт','Komfort')],['business',s('Бизнес','Бизнес','Biznes')],['minivan',s('Минивен','Минивэн','Miniven')]].map(([key,name])=><button key={key} aria-pressed={vehicle===key} onClick={()=>setVehicle(key)}><Car variant={key}/><strong>{name}</strong><small>{s('Ба зудӣ','Скоро','Tez kunda')}</small></button>)}</div><div className="payment-row"><span><Icon name="wallet"/>{t.payment}</span><select aria-label={t.payment} value={pay} onChange={e=>setPay(e.target.value)}><option value="cash">{t.cash}</option><option value="direct_transfer">{t.transfer}</option></select></div><button className="order-button" disabled>{t.request}</button><p className="launch-note">{t.pending}</p></section>
 {editing&&<section className="address-search" role="dialog" aria-modal="true" aria-label={editing==='from'?t.from:t.to}><div className="search-heading"><button className="light" aria-label={m.back} onClick={()=>setEditing(null)}>←</button><h2>{editing==='from'?t.from:t.to}</h2></div><input autoFocus aria-label={m.search} placeholder={m.search} value={q} onChange={e=>setQ(e.target.value)}/><button className="map-pick" onClick={()=>{setEditing(null);setSelected(null)}}>⌖ {m.map}</button><div className="address-results">{matches.map(p=><button key={p.id} onClick={()=>setSelected({lat:p.lat,lon:p.lon,name:pointName(p),detail:pointDetail(p)})}><span>📍</span><div><strong>{pointName(p)}</strong><small>{pointDetail(p)}</small></div><span>›</span></button>)}{q&&!matches.length&&<p>{m.empty}</p>}</div></section>}
 {selected&&<section className="place-detail" role="dialog" aria-modal="true" aria-label={selected.name}><button className="close light" aria-label={m.back} onClick={()=>setSelected(null)}>×</button><small>{active.current==='from'?t.from:t.to}</small><h2>{selected.name}</h2><p>{selected.detail}</p><button onClick={()=>choose(selected)}>{m.select}</button></section>}
 <span className="map-attribution">© OpenStreetMap contributors · Cavi Maps</span></section>
}
